### ISSUE TITLE
Fetch financial data

### ISSUE THREAD

**Issue by FundaSubasi** [FundaSubasi/ai_project_2_group_10#4]

**Comment by bychok** [comment]
https://www.epi.org/data/#/?subject=wage-avg&el=*

**Comment by MxOdele** [comment]
Unemployment:
https://www.epi.org/data/#?subject=unemp

Consumer Confidence Indicator:
https://www.kaggle.com/datasets/iqbalsyahakbar/cci-oecd

Inflation Rate:
https://www.kaggle.com/datasets/pavankrishnanarne/us-inflation-dataset-1947-present

Public Debt:
https://www.kaggle.com/datasets/pavankrishnanarne/us-public-debt-quarterly-data-1996-present
